kind: pipeline
name: default

steps:
- name: code-analysis
pull: if-not-exists
image: aosapps/drone-sonar-plugin
settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token