apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: crater-mysql
  name: crater-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crater-mysql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/crater-net: "true"
        io.kompose.service: crater-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: {{ .Values.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.MYSQL_PASSWORD }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.MYSQL_ROOT_PASSWORD }}
          image: mysql
          livenessProbe:
            exec:
              command:
                - mysql {{ .Values.MYSQL_DATABASE }} --user={{ .Values.MYSQL_USER }} --password={{ .Values.MYSQL_PASSWORD }} --silent --execute "SELECT 1;"
            failureThreshold: 3
            periodSeconds: 120
            timeoutSeconds: 20
          name: crater-mysql
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
