apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: crater-net
spec:
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
      - podSelector: {}

  policyTypes:
  - Ingress
  - Egress