apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: crater-minio-dev
  name: crater-minio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crater-minio-dev
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/crater-net: "true"
        io.kompose.service: crater-minio-dev
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: "MINIO_ROOT_PASSWORD"
              value: {{ .Values.MINIO_USER }}
            - name: "MINIO_ROOT_USER"
              value: {{ .Values.MINIO_PASS }}
          image: quay.io/minio/minio
          name: crater-minio-dev
          ports:
            - containerPort: 9001
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
