name: crater-sh
description: Crater Prod deployment Helm Chart
version: 0.1
apiVersion: v1
keywords:
  - docker-compose
sources:
home:
templates:
  - crater-net-networkpolicy.yaml
  - crater-sh-service.yaml
  - crater-sh-deployment.yaml
    #- crater-lb.yaml
